{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_low/RL_S001__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_low/RL_S001__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RL_S001.txt ; } 2> timing/timing_megan_diamond_RL_S001.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_med/RM2_S001__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_med/RM2_S001__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RM2_S001.txt ; } 2> timing/timing_megan_diamond_RM2_S001.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_med/RM2_S002__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_med/RM2_S002__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RM2_S002.txt ; } 2> timing/timing_megan_diamond_RM2_S002.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S001__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S001__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RH_S001.txt ; } 2> timing/timing_megan_diamond_RH_S001.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S002__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S002__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RH_S002.txt ; } 2> timing/timing_megan_diamond_RH_S002.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S003__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S003__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RH_S003.txt ; } 2> timing/timing_megan_diamond_RH_S003.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S004__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S004__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RH_S004.txt ; } 2> timing/timing_megan_diamond_RH_S004.txt

{ ~/bin/time -f "time result\ncmd:%C\nreal %es\nuser %Us \nsys  %Ss \nmemory:%MKB \ncpu %P" ./megan_diamond_pipeline.sh /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S005__insert_270.fq.R1 /local2/nlapier2/metalign/cami/1cami/challenge_high/RH_S005__insert_270.fq.R2 /local2/nlapier2/metalign/tools/MEGAN6/nr /local2/nlapier2/metalign/tools/MEGAN6/megan-map-Oct2019.db /local2/nlapier2/metalign/cami/1cami/timing/results/megan_diamond_RH_S005.txt ; } 2> timing/timing_megan_diamond_RH_S005.txt

#
