python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RL_S001/ --outdir OPAL/final_profiles/thresh_0pt1pct_RL_S001/ --threshold 0.1 --gold_standard OPAL/final_profiles/RL_S001/goldstandard_low_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RM2_S001/ --outdir OPAL/final_profiles/thresh_0pt1pct_RM2_S001/ --threshold 0.1 --gold_standard OPAL/final_profiles/RM2_S001/goldstandard_medium_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RM2_S002/ --outdir OPAL/final_profiles/thresh_0pt1pct_RM2_S002/ --threshold 0.1 --gold_standard OPAL/final_profiles/RM2_S002/goldstandard_medium_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S001/ --outdir OPAL/final_profiles/thresh_0pt1pct_RH_S001/ --threshold 0.1 --gold_standard OPAL/final_profiles/RH_S001/goldstandard_high_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S002/ --outdir OPAL/final_profiles/thresh_0pt1pct_RH_S002/ --threshold 0.1 --gold_standard OPAL/final_profiles/RH_S002/goldstandard_high_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S003/ --outdir OPAL/final_profiles/thresh_0pt1pct_RH_S003/ --threshold 0.1 --gold_standard OPAL/final_profiles/RH_S003/goldstandard_high_3.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S004/ --outdir OPAL/final_profiles/thresh_0pt1pct_RH_S004/ --threshold 0.1 --gold_standard OPAL/final_profiles/RH_S004/goldstandard_high_4.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S005/ --outdir OPAL/final_profiles/thresh_0pt1pct_RH_S005/ --threshold 0.1 --gold_standard OPAL/final_profiles/RH_S005/goldstandard_high_5.profile

python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RL_S001/ --outdir OPAL/final_profiles/thresh_0pt01pct_RL_S001/ --threshold 0.01 --gold_standard OPAL/final_profiles/RL_S001/goldstandard_low_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RM2_S001/ --outdir OPAL/final_profiles/thresh_0pt01pct_RM2_S001/ --threshold 0.01 --gold_standard OPAL/final_profiles/RM2_S001/goldstandard_medium_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RM2_S002/ --outdir OPAL/final_profiles/thresh_0pt01pct_RM2_S002/ --threshold 0.01 --gold_standard OPAL/final_profiles/RM2_S002/goldstandard_medium_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S001/ --outdir OPAL/final_profiles/thresh_0pt01pct_RH_S001/ --threshold 0.01 --gold_standard OPAL/final_profiles/RH_S001/goldstandard_high_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S002/ --outdir OPAL/final_profiles/thresh_0pt01pct_RH_S002/ --threshold 0.01 --gold_standard OPAL/final_profiles/RH_S002/goldstandard_high_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S003/ --outdir OPAL/final_profiles/thresh_0pt01pct_RH_S003/ --threshold 0.01 --gold_standard OPAL/final_profiles/RH_S003/goldstandard_high_3.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S004/ --outdir OPAL/final_profiles/thresh_0pt01pct_RH_S004/ --threshold 0.01 --gold_standard OPAL/final_profiles/RH_S004/goldstandard_high_4.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/final_profiles/RH_S005/ --outdir OPAL/final_profiles/thresh_0pt01pct_RH_S005/ --threshold 0.01 --gold_standard OPAL/final_profiles/RH_S005/goldstandard_high_5.profile

python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RL_S001/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RL_S001/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RL_S001/goldstandard_low_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RM2_S001/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RM2_S001/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RM2_S001/goldstandard_medium_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RM2_S002/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RM2_S002/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RM2_S002/goldstandard_medium_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S001/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RH_S001/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RH_S001/goldstandard_high_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S002/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RH_S002/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RH_S002/goldstandard_high_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S003/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RH_S003/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RH_S003/goldstandard_high_3.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S004/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RH_S004/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RH_S004/goldstandard_high_4.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S005/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt1pct_RH_S005/ --threshold 0.1 --gold_standard OPAL/custom_kraken2_profiles/RH_S005/goldstandard_high_5.profile

python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RL_S001/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RL_S001/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RL_S001/goldstandard_low_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RM2_S001/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RM2_S001/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RM2_S001/goldstandard_medium_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RM2_S002/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RM2_S002/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RM2_S002/goldstandard_medium_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S001/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RH_S001/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RH_S001/goldstandard_high_1.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S002/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RH_S002/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RH_S002/goldstandard_high_2.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S003/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RH_S003/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RH_S003/goldstandard_high_3.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S004/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RH_S004/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RH_S004/goldstandard_high_4.profile
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/custom_kraken2_profiles/RH_S005/ --outdir OPAL/custom_kraken2_profiles/thresh_0pt01pct_RH_S005/ --threshold 0.01 --gold_standard OPAL/custom_kraken2_profiles/RH_S005/goldstandard_high_5.profile

python Metalign/personal_utils/threshold_abundance.py --indir OPAL/peabody_profiles/no_cutoff/ --outdir OPAL/peabody_profiles/0pt01_cutoff/ --threshold 0.01 --gold_standard OPAL/peabody_profiles/no_cutoff/goldstandard.tsv
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/peabody_profiles/no_cutoff/ --outdir OPAL/peabody_profiles/0pt1_cutoff/ --threshold 0.1 --gold_standard OPAL/peabody_profiles/no_cutoff/goldstandard.tsv
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/peabody_profiles/no_cutoff/ --outdir OPAL/peabody_profiles/1pt0_cutoff/ --threshold 1.0 --gold_standard OPAL/peabody_profiles/no_cutoff/goldstandard.tsv
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/peabody_profiles/no_cutoff/ --outdir OPAL/peabody_profiles/5pt0_cutoff/ --threshold 5.0 --gold_standard OPAL/peabody_profiles/no_cutoff/goldstandard.tsv
python Metalign/personal_utils/threshold_abundance.py --indir OPAL/peabody_profiles/no_cutoff/ --outdir OPAL/peabody_profiles/10pt0_cutoff/ --threshold 10.0 --gold_standard OPAL/peabody_profiles/no_cutoff/goldstandard.tsv

