lmh=(L M2 M2 H H H H H)
lowmedhigh=(low medium medium high high high high high)
s00=(1 1 2 1 2 3 4 5)

for i in 0 1 2 3 4 5 6 7
do
	docker run -v /Users/nathanlapierre/Documents/ucla-research/metalign/OPAL/final_profiles/R${lmh[$i]}_S00${s00[$i]}:/host opal:latest opal.py -g /host/goldstandard_${lowmedhigh[$i]}_${s00[$i]}.profile /host/metalign_R${lmh[$i]}_S00${s00[$i]}.tsv /host/opal_fmt_bracken_results_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_clark_abundances_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_gottcha_abundances_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_megan_diamond_R${lmh[$i]}_S00${s00[$i]}.tsv /host/cami_fmt_metabing2_gpu_R${lmh[$i]}_S00${s00[$i]}.tsv /host/opal_fmt_metaphlan2_results_R${lmh[$i]}_S00${s00[$i]}.txt /host/motus2_default_R${lmh[$i]}_S00${s00[$i]}.txt -l "Metalign, Bracken+Kraken2, CLARK, GOTTCHA, MEGAN+DIAMOND, MetaBinG2, MetaPhlAn2, mOTUs2" -o /host/opal_results/  --ranks superkingdom,species
	docker run -v /Users/nathanlapierre/Documents/ucla-research/metalign/OPAL/final_profiles/thresh_0pt1pct_R${lmh[$i]}_S00${s00[$i]}:/host opal:latest opal.py -g /host/goldstandard_${lowmedhigh[$i]}_${s00[$i]}.profile /host/metalign_R${lmh[$i]}_S00${s00[$i]}.tsv /host/opal_fmt_bracken_results_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_clark_abundances_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_gottcha_abundances_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_megan_diamond_R${lmh[$i]}_S00${s00[$i]}.tsv /host/cami_fmt_metabing2_gpu_R${lmh[$i]}_S00${s00[$i]}.tsv /host/opal_fmt_metaphlan2_results_R${lmh[$i]}_S00${s00[$i]}.txt /host/motus2_default_R${lmh[$i]}_S00${s00[$i]}.txt -l "Metalign, Bracken+Kraken2, CLARK, GOTTCHA, MEGAN+DIAMOND, MetaBinG2, MetaPhlAn2, mOTUs2" -o /host/opal_results/  --ranks superkingdom,species
	docker run -v /Users/nathanlapierre/Documents/ucla-research/metalign/OPAL/final_profiles/thresh_0pt01pct_R${lmh[$i]}_S00${s00[$i]}:/host opal:latest opal.py -g /host/goldstandard_${lowmedhigh[$i]}_${s00[$i]}.profile /host/metalign_R${lmh[$i]}_S00${s00[$i]}.tsv /host/opal_fmt_bracken_results_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_clark_abundances_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_gottcha_abundances_R${lmh[$i]}_S00${s00[$i]}.txt /host/cami_fmt_megan_diamond_R${lmh[$i]}_S00${s00[$i]}.tsv /host/cami_fmt_metabing2_gpu_R${lmh[$i]}_S00${s00[$i]}.tsv /host/opal_fmt_metaphlan2_results_R${lmh[$i]}_S00${s00[$i]}.txt /host/motus2_default_R${lmh[$i]}_S00${s00[$i]}.txt -l "Metalign, Bracken+Kraken2, CLARK, GOTTCHA, MEGAN+DIAMOND, MetaBinG2, MetaPhlAn2, mOTUs2" -o /host/opal_results/  --ranks superkingdom,species
done
